* Instructions

** If you are presenting this unit:

*** Upload instructions
Upload all content relating to the delivery of your unit. Include the
prework, slides, content etc.

Please use these filenames:
- *homework.md*, *homework.pdf*, or *homework.docx* for the homework
  assignment
- *prework.md*, *prework.pdf*, or *prework.docx* if you are giving
  links to videos or online resources for prework
- Other files should be given names that make sense
*** Assigning the work
- make sure to post the prework one week before your presentation in
  the #cstopics-async channel.
- make sure to post the homework after your group presentation in the
  #cstopics-hw channel.
  
** If you are completing the homework for this unit:

The homework will be posted in the #cstopics-hw channel.

Upload your solutions to the assigned homework in the appropriate
folder. Make sure to use the filenames specified in the assignments.



* Last name: Park
* First name: Moo Joon (Mike)
* Github username: michaelpark677

* Instructions:

Fill out the top of this form, commit and push it back to GitHub.

** For the topic you are delivering:

Upload all content relating to the delivery of your unit. Include the
prework, slides, content etc.

Please use these filenames:
- *homework.md*, *homework.pdf*, or *homework.docx* for the homework
  assignment
- *prework.md*, *prework.pdf*, or *prework.docx* if you are giving
  links to videos or online resources for prework
- Other files should be given names that make sense

** For all other topics:

Upload your solutions to the assigned homework in the appropriate
folder. Make sure to use the filenames specified in the assignments.

* Last name: Park
* First name: Moo Joon (Mike)
* Github username: michaelpark677

* Instructions:

Fill out the top of this form, commit and push it back to GitHub.

** For the topic you are delivering:

Upload all content relating to the delivery of your unit. Include the
prework, slides, content etc.

Please use these filenames:
- *homework.md*, *homework.pdf*, or *homework.docx* for the homework
  assignment
- *prework.md*, *prework.pdf*, or *prework.docx* if you are giving
  links to videos or online resources for prework
- Other files should be given names that make sense

** For all other topics:

Upload your solutions to the assigned homework in the appropriate
folder. Make sure to use the filenames specified in the assignments.

https://replit.com/@michaelpark677/Demo-Flask-Project#main.py

Link to the session homework:
https://replit.com/join/luhuntjhtx-michaelpark677

Link to the forms homework: (* I couldn't get this code to output correctly. I tried debugging but it wouldn't show the form as displayed in the video. The only output it kept showing was "Hello from Flask!"
https://replit.com/join/gzfqsfbhxu-michaelpark677
